name: google-gn

on:
  push:
    paths:
      - 'Dockerfile'
      - 'bake.hcl'
      - 'version'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: VERSION="$(cat ./version)" docker buildx bake -f bake.hcl --push